import { ListTodo } from "src/types";
import { getToday, getTommorow } from "./dateFunc";

export const EXAMPLE_MY_TODO_LIST: ListTodo[] = [
  {
    id: "18",
    task: `C7`,
    userId: "",
    sortKey: 7,
    dueDate: "",
    completeDate: "",
    isDone: false,
    createAt: getToday(),
    updateAt: "2022-03-01",
  },
  {
    id: "17",
    task: `C6`,
    userId: "",
    sortKey: 6,
    dueDate: "",
    completeDate: "",
    isDone: false,
    createAt: getToday(),
    updateAt: "2022-03-01",
  },
  {
      id: "16",
      task: `C5`,
      userId: "",
      sortKey: 5,
      dueDate: "",
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "15",
      task: `C4`,
      userId: "",
      sortKey: 4,
      dueDate: "",
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "14",
      task: `C3`,
      userId: "",
      sortKey: 3,
      dueDate: "",
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "13",
      task: `C2`,
      userId: "",
      sortKey: 2,
      dueDate: "",
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "12",
      task: `C1`,
      userId: "",
      sortKey: 1,
      dueDate: "",
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
    id: "11",
    task: `B6`,
    userId: "",
    sortKey: 6,
    dueDate: getTommorow(),
    completeDate: "",
    isDone: false,
    createAt: getToday(),
    updateAt: "2022-03-01",
  },
  {
      id: "10",
      task: `B5`,
      userId: "",
      sortKey: 5,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "9",
      task: `B4`,
      userId: "",
      sortKey: 4,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "8",
      task: `B3`,
      userId: "",
      sortKey: 3,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "7",
      task: `B2`,
      userId: "",
      sortKey: 2,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "6",
      task: `B1`,
      userId: "",
      sortKey: 1,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "5",
      task: `A5`,
      userId: "",
      sortKey: 5,
      dueDate: getToday(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: "2022-03-01",
    },
    {
      id: "4",
      task: `A4`,
      userId: "",
      sortKey: 4,
      dueDate: getToday(),
      completeDate: getToday(),
      isDone: true,
      createAt: getToday(),
      updateAt: getToday(),
    },
    {
      id: "3",
      task: `A3`,
      userId: "",
      sortKey: 3,
      dueDate: getTommorow(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: getToday(),
    },
    {
      id: "2",
      task: `A2`,
      userId: "",
      sortKey: 2,
      dueDate: getToday(),
      completeDate: "",
      isDone: false,
      createAt: getToday(),
      updateAt: getToday(),
    },
    {
      id: "1",
      task: `A1`,
      userId: "",
      sortKey: 1,
      dueDate: getToday(),
      completeDate: "",
      isDone: true,
      createAt: getToday(),
      updateAt: getToday(),
    },
  ];
  